website/main/urls.py
from django.urls import path
from main.views import home, indexItems, about_us, catalog, add_item, update_item, delete_item, order, order_list, order_detail

app_name = 'main'

urlpatterns = [
    path('', home, name='home'),
    path('about-us/', about_us, name='about-us'),
    path('catalog/', catalog, name='catalog'),
    path('add-item/', add_item, name='add-item'),
    path('update-item/<int:my_id>/', update_item, name='update-item'),
    path('delete-item/<int:my_id>/', delete_item, name='delete-item'),
    path('catalog/<int:my_id>/', indexItems, name='detail'),
    path('order/', order, name='order'),
    path('order-list/', order_list, name='order-list'),
    path('order-list/<int:my_id>/', order_detail, name='order-detail'),
]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/main/models.py
from django.db import models

class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    description = models.CharField(max_length=200)
    image = models.ImageField(blank=True, upload_to='png')

    def __str__(self):
        return self.name
    
class Order(models.Model):
    user = models.CharField(max_length=100)
    products = models.CharField(max_length=200)
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.user

website/main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Product, Order
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

def news(request):
    return render(request, 'main/news.html')

def home(request):
    return render(request, 'main/home.html')

def about_us(request):
    return render(request, 'main/about-us.html')

def indexItems(request, my_id):
    item = Product.objects.get(id=my_id)
    context = {
        'item':item
    }
    return render(request, 'main/detail.html', context)

def catalog(request):
    page_obj = items = Product.objects.all()

    item_name = request.GET.get('search')
    if item_name != '' and item_name is not None:
        page_obj = items.filter(name__icontains=item_name)

    paginator = Paginator(items, 100)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obg': page_obj
    }
    return render(request, 'main/catalog.html', context)

@login_required
def add_item(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        price = request.POST.get('price')
        description = request.POST.get('description')
        image = request.FILES['upload']
        item = Product(name=name, price=price, description=description, image=image)
        item.save()
        return redirect('/catalog/')
    return render(request, 'main/add-item.html')

@login_required
def update_item(request, my_id):
    item = Product.objects.get(id=my_id)
    if request.method == 'POST':
        item.name = request.POST.get('name')
        item.price = request.POST.get('price')
        item.description = request.POST.get('description')
        item.image = request.FILES.get('upload', item.image)
        item.save()
        return redirect('/catalog/')
    context = {
        'item': item
    }
    return render(request, 'main/update-item.html', context)

@login_required
def delete_item(request, my_id):
    item = Product.objects.get(id=my_id)
    if request.method == 'POST':
        item.delete()
        return redirect('/catalog/')
    context = {
        'item': item
    }
    return render(request, 'main/delete-item.html', context)

def order(request):
    if request.method == 'POST':
        user = request.POST.get('user')
        products = request.POST.get('products')
        description = request.POST.get('description')
        ord = Order(user=user, products=products, description=description)
        ord.save()
        return redirect('/catalog/')
    return render(request, 'main/order.html')

@login_required
def order_list(request):
    orders = Order.objects.all()
    context = {'orders':orders}
    return render(request, 'main/order-list.html', context)

@login_required
def order_detail(request, my_id):
    ord = Order.objects.get(id=my_id)
    context = {
        'ord':ord
    }
    return render(request, 'main/order-detail.html', context)

website/main/templates/main/about-us.html
{% extends 'main/layout.html' %}

{% block title %}О нас{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 py-3">
                <div class="bg-white product-content p-3 h-100">
                    <h2>Наши контакты:</h2>
                    <h4>Горячая линия: <a href="tel:+70000000000" class="ms-2">+7-000-000-00-00</a></h4>
                    <h4>Наши сотсети:</h4>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

website/main/templates/main/add-item.html
{% extends 'main/layout.html' %}

{% block title %}Добавить товар{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-4"></div>
        <div class="col-12 col-lg-4">
            <div class="py-3">
                <p></p>
            </div>
            <div class="add-item py-2 px-2">
                <div class="add-item-header d-flex justify-content-center">
                    <h3>Добавить карточку в каталог</h3>
                </div>
                <form method="post" class="add-item-main" enctype="multipart/form-data">
                    {% csrf_token %}
                    <label>Имя товара:</label>
                    <input type="text" class="form-control" placeholder="Имя товара" aria-label="Имя товара" aria-describedby="basic-addon1" id="name" name="name">
                    <label>Цена товара:</label>
                    <input type="text" class="form-control" placeholder="Цена товара" aria-label="Цена товара" aria-describedby="basic-addon1" id="price" name="price">
                    <label>Описание товара:</label>
                    <input type="text" class="form-control" placeholder="Описание товара" aria-label="Описание товара" aria-describedby="basic-addon1" id="description" name="description">
                    <label>Изображение товара:</label>
                    <input type="file" class="form-control" accept="image/*" aria-describedby="basic-addon1" id="upload" name="upload">
                    <button type="submit" class="btn btn-outline-secondary" name="add-item">Добавить</button>
                </form>
            </div>
        </div>
        <div class="col-lg-4"></div>
    </div>
</div>


{% endblock %}

website/main/templates/main/catalog.html
{% extends 'main/layout.html' %}

{% block title %}Каталог{% endblock %}

{% block content %}
    <section class="">
        <div class="container-fluid">
            <div class="row mb-5">
                <div class="col-12">
                    <h2 class="section-title">
                        <span>Каталог</span>
                    </h2>
                </div>
            </div>
            <div class="row">
                {% for item in page_obg %}
                <div class="col-lg-3 col-md-4 col-sm-6 mb-3">
                    <div class="product-card">
                        <div class="product-thumb">
                            <a href="{% url 'main:detail' item.id %}"><img src="{{item.image.url}}" alt=""></a>
                        </div>
                        <div class="product-name">
                            <h4>
                                <a href="{% url 'main:detail' item.id %}">{{item.name}} </a>
                            </h4>
                            <p class="product-description">
                                {{item.description}}
                            </p>
                            <div class="product-details  d-flex justify-content-between">
                                <div class="product-price">
                                    {{item.price}}₽
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>

{% endblock %}

<!--
{% for item in items %}
        <a href="{% url 'main:detail' item.id %}">
        ID: {{item.id}} | Имя: {{item.name}} | Цена: {{item.price}} | Описание: {{item.description}} <br/>
            <img src="{{item.image.url}}" alt="">
        </a>
        {% endfor %}
-->

website/main/templates/main/delete-item.html
{% extends 'main/layout.html' %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-4"></div>
        <div class="col-12 col-lg-4">
            <div class="py-3">
                <p></p>
            </div>
            <div class="add-item py-3 px-3">
                <div class="update-item-header d-flex justify-content-center">
                    <h3>Удалить товар?</h3>
                </div>
                <form method="post" class="update-item-main" enctype="multipart/form-data">
                    {% csrf_token %}
                    <label>Имя товара:</label>
                    <p>{{ item.name }}</p>
                    <label>Изображение товара:</label>
                    <img src="{{ item.image.url }}" alt="" width="70" height="70">
                    <div class="delete-item-buttons">
                        <button type="submit" class="btn btn-outline-danger" name="add-item">Удалить</button>
                        <button class="btn btn-outline-success"><a href="{% url 'main:detail' item.id %}"></a> Вернуться</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-lg-4"></div>
    </div>
</div>
{% endblock %}

website/main/templates/main/detail.html
{% extends 'main/layout.html' %}

{% block title %}{{item.name}}{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-5 col-lg-4 py-3">
                <div class="bg-white product-content-image">
                    <img src="{{ item.image.url }}" class="d-block w-100" alt="">
                </div>
            </div>
            <div class="col-md-7 col-lg-8 py-3">
                <div class="bg-white product-content p-3 h-100">
                    <h2>{{ item.name }}</h2>
                    <h4>ID: {{ item.id }}</h4>
                    <div class="prodct-price">
                        <h4>Цена: {{ item.price }}₽</h4>
                    </div>
                    <p>{{ item.description }}</p>
                    <div class="product-content-button">
                        {% if user.is_superuser %}
                        <button class="btn btn-outline-secondary"><a href="{% url 'main:update-item' item.id %}">Изменить</a></button>
                        <button class="btn btn-outline-danger"><a href="{% url 'main:delete-item' item.id %}">Удалить</a></button>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


website/main/templates/main/home.html
{% extends 'main/layout.html' %}
{% load static %}

{% block title %}Главная страница{% endblock %}

{% block content %}
    <div id="carousel" class="carousel slide
" data-bs-ride="carousel">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'main/png/slide1.jpg' %}" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h2>Пчелиный мёд</h2>
                    <p></p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'main/png/slide2.jpg' %}" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h2>Пчелиные соты</h2>
                    <p></p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'main/png/slide3.jpg' %}" class="d-block w-100 h-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h2>Продукты из пчелиного меда</h2>
                    <p></p>
                </div>
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Предыдущий</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Следующий</span>
        </button>
    </div>

    <section class="advantages">
        <div class="container-fluid">
            <div class="items">
                <div class="row gy-3">
                    <div class="col-lg-4">
                        <div class="item">
                            <p><i class="fas fa-shipping-fast"></i></p>
                            <p>Быстрая доставка</p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="item">
                            <p><i class="fas fa-thumbs-up"></i></p>
                            <p>Качественная продукция</p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="item">
                            <p><i class="fas fa-headset"></i></p>
                            <p>Горячая линия</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

website/main/templates/main/layout.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://libs.cdnjs.net/font-awesome/6.5.1/css/all.css">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
</head>
<body>
    <div class="wrapper">
        <header class="header py-2">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-6 col-lg-6">
                        <a href="{% url 'main:home' %}" class="header-logo h2">Honey-L1fe</a>
                    </div>
                    <div class="col-lg-5 d-none d-lg-block">
                        <div class="header-number d-flex align-items-center h-100 justify-content-end"> <!-- Выравнивание на высоту 100% -->
                            <i class="fa-solid fa-phone"></i>
                            <a href="tel:+70000000000" class="ms-2">+7-000-000-00-00</a>
                        </div>
                    </div>
                    <div class="col-6 col-lg-1">
                        <div class="header-contacts d-flex justify-content-end align-items-center h-100">
                            <li><a href=""><i class="fa-brands fa-youtube"></i></a></li>
                            <li><a href=""><i class="fa-brands fa-facebook-f"></i></a></li>
                            <li><a href=""><i class="fa-brands fa-instagram"></i></a></li>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <nav class="navbar navbar-expand-lg navbar-light sticky-top" style="background-color: #f0c905">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-expanded="false" aria-label="Переключатель навигации">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="offcanvas offcanvas-start" id="offcanvasNavbar" tabindex="-1" aria-labelledby="offcanvasNavbarLabel">
                    <div class="offcanvas-header">
                        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Навигационная панель</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'main:home' %}">Главная</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'main:catalog' %}">Каталог</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'main:about-us' %}">О нас</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'main:order' %}">Сделать заказ</a>
                            </li>
                            {% if user.is_superuser %}
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'main:order-list' %}">Список заказов</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'main:add-item' %}">Создать товар</a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
        <main class="main">
            {% block content %}
            {% endblock %}
        </main>
        <footer class="footer py-2">
            ©️HONEY-L1FE, 2024
        </footer>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>

website/main/templates/main/news.html
{% extends 'main/layout.html' %}

{% block title %}Новости{% endblock %}

{% block content %}
    <p>Новости</p>
{% endblock %}

website/main/templates/main/order-detail.html
{% extends 'main/layout.html' %}

{% block title %}Заказ №{{ord.id}}{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 py-3">
                <div class="bg-white product-content p-3 h-100">
                    <h2>Заказ №{{ ord.id }}</h2>
                    <h4>Заказчик: {{ ord.user }}</h4>
                    <div class="prodct-price">
                        <p>Товары: {{ ord.products }}</p>
                    </div>
                    <p>Адрес: {{ ord.description }}</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

website/main/templates/main/order-list.html
{% extends 'main/layout.html' %}

{% block title %}Список заказов{% endblock %}

{% block content %}
    <section class="">
        <div class="container-fluid">
            <div class="row mb-5">
                <div class="col-12">
                    <h2 class="section-title">
                        <span>Список заказов</span>
                    </h2>
                </div>
            </div>
            <div class="row">
                {% for ord in orders %}
                <div class="col-lg-3 col-md-4 col-sm-6 mb-3">
                    <div class="product-card">
                        <div class="product-name">
                            <h4>
                                <a href="{% url 'main:order-detail' ord.id %}">Заказ №{{ord.id}} </a>
                            </h4>
                            <p>
                                <a href="{% url 'main:order-detail' ord.id %}">Заказчик: {{ord.user}} </a>
                            </p>
                            <p class="product-description">
                                Товары: {{ord.products}}
                            </p>
                            <div class="product-details  d-flex justify-content-between">
                                <div class="product-price">
                                    Адрес: {{ord.description}}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

website/main/templates/main/order.html
{% extends 'main/layout.html' %}

{% block title %}Сделать заказ{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-4"></div>
        <div class="col-12 col-lg-4">
            <div class="py-3">
                <p></p>
            </div>
            <div class="add-item py-2 px-2">
                <div class="add-item-header d-flex justify-content-center">
                    <h3>Создать заказ</h3>
                </div>
                <form method="post" class="add-item-main" enctype="multipart/form-data">
                    {% csrf_token %}
                    <label>ФИО:</label>
                    <input type="text" class="form-control" placeholder="ФИО" aria-label="ФИО" aria-describedby="basic-addon1" id="user" name="user">
                    <label>Товары (Написать ID товара, указанный на его карточке, а также его количество. Пример: ID1 - 1 штука, ID3 - 4 штуки.):</label>
                    <input type="text" class="form-control" placeholder="Товары" aria-label="Товары" aria-describedby="basic-addon1" id="products" name="products">
                    <label>Адрес:</label>
                    <input type="text" class="form-control" placeholder="Адрес" aria-label="Описание товара" aria-describedby="basic-addon1" id="description" name="description">
                    <p>Оплата при получении!</p>
                    <button type="submit" class="btn btn-outline-secondary" name="order">Создать</button>
                </form>
            </div>
        </div>
        <div class="col-lg-4"></div>
    </div>
</div>


{% endblock %}

website/main/templates/main/update-item.html
{% extends 'main/layout.html' %}

{% block title %}Изменить товар{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-4"></div>
        <div class="col-12 col-lg-4">
            <div class="py-3">
                <p></p>
            </div>
            <div class="add-item py-3 px-3">
                <div class="update-item-header d-flex justify-content-center">
                    <h3>Изменить товар в каталоге</h3>
                </div>
                <form method="post" class="update-item-main" enctype="multipart/form-data">
                    {% csrf_token %}
                    <label>Имя товара:</label>
                    <input type="text" class="form-control" placeholder="Имя товара" aria-label="Имя товара" value='{{ item.name }}' aria-describedby="basic-addon1" id="name" name="name">
                    <label>Цена товара:</label>
                    <input type="text" class="form-control" placeholder="Цена товара" aria-label="Цена товара" value='{{ item.price }}' aria-describedby="basic-addon1" id="price" name="price">
                    <label>Описание товара:</label>
                    <input type="text" class="form-control" placeholder="Описание товара" aria-label="Описание товара" value='{{ item.description }}' aria-describedby="basic-addon1" id="description" name="description">
                    <label>Изображение товара:</label>
                    <img src="{{ item.image.url }}" alt="" width="70" height="70">
                    <input type="file" class="form-control" accept="image/*" aria-describedby="basic-addon1" id="upload" name="upload">
                    <button type="submit" class="btn btn-outline-secondary" name="add-item">Изменить</button>
                </form>
            </div>
        </div>
        <div class="col-lg-4"></div>
    </div>
</div>


{% endblock %}